################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
App/Src \
Core/Src \
Core/Startup \
Drivers/STM32H7xx_HAL_Driver/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
TouchGFX/App \
TouchGFX/build/App/Src \
TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/accueil_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/attente_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/bouclage_ecs_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/code_numerique_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/code_web_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/configuration_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/containers \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/date_heure_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/derogation_ecs_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/derogation_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/eau_chaude_sanitaire_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/energies_cumul_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/energies_histo_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/energies_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/erreurs_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/historique_defauts_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/historiques_fonctionnement_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/infos_systeme_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_appoint_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_chauffe_dalle_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_circuit_captage_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_circuit_primaire_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_clavier_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_config_hydrau_rapide_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_config_in_out_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_courbe_loi_d_eau_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_cycle_legionel_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_inhibition_ejp_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_puissance_appoint_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_puissance_echangeur_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_simultane_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_solaire_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hydraulique_config_zone_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hydraulique_gestion_circulateur_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hydraulique_numero_sonde_rf_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hydraulique_param_comp_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hydraulique_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hydraulique_sonde_modbus_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hydraulique_sonde_rf_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hysteresis_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_param_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_piscine_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_piscine_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_wattmetre_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/langue_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/luminosite_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/maintenance_fct_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/maintenance_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/maintenance_test_composants_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/multizones_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/page_oui_non_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/parametres_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/piscine_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/position_ecran_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/programmation_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/programmation_zoom_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/secours_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/synoptique_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/test_pac_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_choix_fluide_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_choix_modele_pac_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_config_additionnelle_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_config_ajpac_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_config_geotwin_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_config_inverterra_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_param_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/vacances_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/variables_systeme_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/veille_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/zone_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__generated \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src/video \
TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
TouchGFX/build/MINGW32_NT-6.2/gui/src/accueil_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/attente_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/bouclage_ecs_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/code_numerique_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/code_web_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
TouchGFX/build/MINGW32_NT-6.2/gui/src/configuration_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/containers \
TouchGFX/build/MINGW32_NT-6.2/gui/src/date_heure_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/derogation_ecs_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/derogation_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/eau_chaude_sanitaire_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/energies_cumul_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/energies_histo_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/energies_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/erreurs_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/historique_defauts_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/historiques_fonctionnement_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/infos_systeme_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_appoint_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_chauffe_dalle_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_circuit_captage_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_circuit_primaire_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_clavier_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_config_hydrau_rapide_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_config_in_out_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_courbe_loi_d_eau_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_cycle_legionel_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_inhibition_ejp_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_puissance_appoint_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_puissance_echangeur_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_simultane_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_solaire_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hydraulique_config_zone_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hydraulique_gestion_circulateur_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hydraulique_numero_sonde_rf_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hydraulique_param_comp_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hydraulique_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hydraulique_sonde_modbus_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hydraulique_sonde_rf_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hysteresis_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_param_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_piscine_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_piscine_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_wattmetre_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/langue_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/luminosite_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/maintenance_fct_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/maintenance_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/maintenance_test_composants_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
TouchGFX/build/MINGW32_NT-6.2/gui/src/multizones_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/page_oui_non_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/parametres_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/piscine_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/position_ecran_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/programmation_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/programmation_zoom_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/secours_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/synoptique_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/test_pac_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_choix_fluide_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_choix_modele_pac_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_config_additionnelle_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_config_ajpac_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_config_geotwin_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_config_inverterra_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_param_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/vacances_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/variables_systeme_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/veille_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/zone_screen \
TouchGFX/build/MINGW32_NT-6.2/simulator \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/accueil_screen \
TouchGFX/generated/gui_generated/src/attente_screen \
TouchGFX/generated/gui_generated/src/bouclage_ecs_screen \
TouchGFX/generated/gui_generated/src/code_numerique_screen \
TouchGFX/generated/gui_generated/src/code_web_screen \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/configuration_screen \
TouchGFX/generated/gui_generated/src/containers \
TouchGFX/generated/gui_generated/src/date_heure_screen \
TouchGFX/generated/gui_generated/src/derogation_ecs_screen \
TouchGFX/generated/gui_generated/src/derogation_screen \
TouchGFX/generated/gui_generated/src/eau_chaude_sanitaire_screen \
TouchGFX/generated/gui_generated/src/energies_cumul_screen \
TouchGFX/generated/gui_generated/src/energies_histo_screen \
TouchGFX/generated/gui_generated/src/energies_screen \
TouchGFX/generated/gui_generated/src/erreurs_screen \
TouchGFX/generated/gui_generated/src/historique_defauts_screen \
TouchGFX/generated/gui_generated/src/historiques_fonctionnement_screen \
TouchGFX/generated/gui_generated/src/infos_systeme_screen \
TouchGFX/generated/gui_generated/src/installation_appoint_screen \
TouchGFX/generated/gui_generated/src/installation_chauffe_dalle_screen \
TouchGFX/generated/gui_generated/src/installation_circuit_captage_screen \
TouchGFX/generated/gui_generated/src/installation_circuit_primaire_screen \
TouchGFX/generated/gui_generated/src/installation_clavier_screen \
TouchGFX/generated/gui_generated/src/installation_config_hydrau_rapide_screen \
TouchGFX/generated/gui_generated/src/installation_config_in_out_screen \
TouchGFX/generated/gui_generated/src/installation_courbe_loi_d_eau_screen \
TouchGFX/generated/gui_generated/src/installation_ecs_avances_screen \
TouchGFX/generated/gui_generated/src/installation_ecs_cycle_legionel_screen \
TouchGFX/generated/gui_generated/src/installation_ecs_inhibition_ejp_screen \
TouchGFX/generated/gui_generated/src/installation_ecs_puissance_appoint_screen \
TouchGFX/generated/gui_generated/src/installation_ecs_puissance_echangeur_screen \
TouchGFX/generated/gui_generated/src/installation_ecs_screen \
TouchGFX/generated/gui_generated/src/installation_ecs_simultane_screen \
TouchGFX/generated/gui_generated/src/installation_ecs_solaire_screen \
TouchGFX/generated/gui_generated/src/installation_hydraulique_config_zone_screen \
TouchGFX/generated/gui_generated/src/installation_hydraulique_gestion_circulateur_screen \
TouchGFX/generated/gui_generated/src/installation_hydraulique_numero_sonde_rf_screen \
TouchGFX/generated/gui_generated/src/installation_hydraulique_param_comp_screen \
TouchGFX/generated/gui_generated/src/installation_hydraulique_screen \
TouchGFX/generated/gui_generated/src/installation_hydraulique_sonde_modbus_screen \
TouchGFX/generated/gui_generated/src/installation_hydraulique_sonde_rf_screen \
TouchGFX/generated/gui_generated/src/installation_hysteresis_screen \
TouchGFX/generated/gui_generated/src/installation_param_avances_screen \
TouchGFX/generated/gui_generated/src/installation_piscine_avances_screen \
TouchGFX/generated/gui_generated/src/installation_piscine_screen \
TouchGFX/generated/gui_generated/src/installation_screen \
TouchGFX/generated/gui_generated/src/installation_wattmetre_screen \
TouchGFX/generated/gui_generated/src/langue_screen \
TouchGFX/generated/gui_generated/src/luminosite_screen \
TouchGFX/generated/gui_generated/src/maintenance_fct_avances_screen \
TouchGFX/generated/gui_generated/src/maintenance_screen \
TouchGFX/generated/gui_generated/src/maintenance_test_composants_screen \
TouchGFX/generated/gui_generated/src/multizones_screen \
TouchGFX/generated/gui_generated/src/page_oui_non_screen \
TouchGFX/generated/gui_generated/src/parametres_screen \
TouchGFX/generated/gui_generated/src/piscine_screen \
TouchGFX/generated/gui_generated/src/position_ecran_screen \
TouchGFX/generated/gui_generated/src/programmation_screen \
TouchGFX/generated/gui_generated/src/programmation_zoom_screen \
TouchGFX/generated/gui_generated/src/secours_screen \
TouchGFX/generated/gui_generated/src/synoptique_screen \
TouchGFX/generated/gui_generated/src/test_pac_screen \
TouchGFX/generated/gui_generated/src/usine_choix_fluide_screen \
TouchGFX/generated/gui_generated/src/usine_choix_modele_pac_screen \
TouchGFX/generated/gui_generated/src/usine_config_additionnelle_screen \
TouchGFX/generated/gui_generated/src/usine_config_ajpac_screen \
TouchGFX/generated/gui_generated/src/usine_config_geotwin_screen \
TouchGFX/generated/gui_generated/src/usine_config_inverterra_screen \
TouchGFX/generated/gui_generated/src/usine_param_avances_screen \
TouchGFX/generated/gui_generated/src/usine_screen \
TouchGFX/generated/gui_generated/src/vacances_screen \
TouchGFX/generated/gui_generated/src/variables_systeme_screen \
TouchGFX/generated/gui_generated/src/veille_screen \
TouchGFX/generated/gui_generated/src/zone_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/images/src/__generated \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/accueil_screen \
TouchGFX/gui/src/attente_screen \
TouchGFX/gui/src/bouclage_ecs_screen \
TouchGFX/gui/src/code_numerique_screen \
TouchGFX/gui/src/code_web_screen \
TouchGFX/gui/src/common \
TouchGFX/gui/src/configuration_screen \
TouchGFX/gui/src/containers \
TouchGFX/gui/src/date_heure_screen \
TouchGFX/gui/src/derogation_ecs_screen \
TouchGFX/gui/src/derogation_screen \
TouchGFX/gui/src/eau_chaude_sanitaire_screen \
TouchGFX/gui/src/energies_cumul_screen \
TouchGFX/gui/src/energies_histo_screen \
TouchGFX/gui/src/energies_screen \
TouchGFX/gui/src/erreurs_screen \
TouchGFX/gui/src/historique_defauts_screen \
TouchGFX/gui/src/historiques_fonctionnement_screen \
TouchGFX/gui/src/infos_systeme_screen \
TouchGFX/gui/src/installation_appoint_screen \
TouchGFX/gui/src/installation_chauffe_dalle_screen \
TouchGFX/gui/src/installation_circuit_captage_screen \
TouchGFX/gui/src/installation_circuit_primaire_screen \
TouchGFX/gui/src/installation_clavier_screen \
TouchGFX/gui/src/installation_config_hydrau_rapide_screen \
TouchGFX/gui/src/installation_config_in_out_screen \
TouchGFX/gui/src/installation_courbe_loi_d_eau_screen \
TouchGFX/gui/src/installation_ecs_avances_screen \
TouchGFX/gui/src/installation_ecs_cycle_legionel_screen \
TouchGFX/gui/src/installation_ecs_inhibition_ejp_screen \
TouchGFX/gui/src/installation_ecs_puissance_appoint_screen \
TouchGFX/gui/src/installation_ecs_puissance_echangeur_screen \
TouchGFX/gui/src/installation_ecs_screen \
TouchGFX/gui/src/installation_ecs_simultane_screen \
TouchGFX/gui/src/installation_ecs_solaire_screen \
TouchGFX/gui/src/installation_hydraulique_config_zone_screen \
TouchGFX/gui/src/installation_hydraulique_gestion_circulateur_screen \
TouchGFX/gui/src/installation_hydraulique_numero_sonde_rf_screen \
TouchGFX/gui/src/installation_hydraulique_param_comp_screen \
TouchGFX/gui/src/installation_hydraulique_screen \
TouchGFX/gui/src/installation_hydraulique_sonde_modbus_screen \
TouchGFX/gui/src/installation_hydraulique_sonde_rf_screen \
TouchGFX/gui/src/installation_hysteresis_screen \
TouchGFX/gui/src/installation_param_avances_screen \
TouchGFX/gui/src/installation_piscine_avances_screen \
TouchGFX/gui/src/installation_piscine_screen \
TouchGFX/gui/src/installation_screen \
TouchGFX/gui/src/installation_wattmetre_screen \
TouchGFX/gui/src/langue_screen \
TouchGFX/gui/src/luminosite_screen \
TouchGFX/gui/src/maintenance_fct_avances_screen \
TouchGFX/gui/src/maintenance_screen \
TouchGFX/gui/src/maintenance_test_composants_screen \
TouchGFX/gui/src/model \
TouchGFX/gui/src/multizones_screen \
TouchGFX/gui/src/page_oui_non_screen \
TouchGFX/gui/src/parametres_screen \
TouchGFX/gui/src/piscine_screen \
TouchGFX/gui/src/position_ecran_screen \
TouchGFX/gui/src/programmation_screen \
TouchGFX/gui/src/programmation_zoom_screen \
TouchGFX/gui/src/secours_screen \
TouchGFX/gui/src/synoptique_screen \
TouchGFX/gui/src/test_pac_screen \
TouchGFX/gui/src/usine_choix_fluide_screen \
TouchGFX/gui/src/usine_choix_modele_pac_screen \
TouchGFX/gui/src/usine_config_additionnelle_screen \
TouchGFX/gui/src/usine_config_ajpac_screen \
TouchGFX/gui/src/usine_config_geotwin_screen \
TouchGFX/gui/src/usine_config_inverterra_screen \
TouchGFX/gui/src/usine_param_avances_screen \
TouchGFX/gui/src/usine_screen \
TouchGFX/gui/src/vacances_screen \
TouchGFX/gui/src/variables_systeme_screen \
TouchGFX/gui/src/veille_screen \
TouchGFX/gui/src/zone_screen \
TouchGFX/target \
TouchGFX/target/generated \
USB_DEVICE/App \
USB_DEVICE/Target \

